swagger: '2.0'
info:
  version: '0.1.0'
  title: my simple api
  description: An API to demonstrate Swagger
host: localhost:8080
basePath: /api
schemes:
  - http
paths:
  /user:
    post:
      description: Create a user
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all users
      operationId: getAllUsers
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
  /user/{id}:
    put:
      description: Update a user
      operationId: updateUser
      consumes:
        - application/json
        parameters:
          - name: user
            in: body
            required: true
            schema:
              $ref: '#/definitions/User'
        responses:
          '201':
            description: updated
            schema:
              type: object
    delete:
        description: Delete a user
        operationId: updateUser
        consumes:
          - application/json
          parameters:
            - name: user
              in: body
              required: true
              schema:
                $ref: '#/definitions/User'
          responses:
            '201':
              description: deleted
              schema:
                type: object
    get:
      description: Get a user
      operationId: getUser
      consumes:
        - application/json
        parameters:
          - name: user
            in: body
            required: true
            schema:
              $ref: '#/definitions/User'
        responses:
          '200':
            description: success
            schema:
              items:
                $ref: '#/definitions/User'

definitions:
  User:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string